export * from "./authentication/authentication-slice"
export * from "./pokemon/pokemon-slice"
export * from "./poketeam/poketeam-slice"
export { default as authenticationReducer } from "./authentication/authentication-slice"
export { default as pokemonReducer } from "./pokemon/pokemon-slice"
export { default as poketeamReducer } from "./poketeam/poketeam-slice"
